DefaultContentLanguage = "fr"
#baseURL = "/" 
# Dist :
baseURL = "https://bastiencornier.com/"
title = "Bastien Cornier"
theme = "portfolio"
description = "Bastien Cornier, Creative & Front-end Developer Freelance based in France. Offers original and innovative experiences for web agencies, startups and companies."
Paginate = 1000
canonifyurls = true

[[menu.main]]
    name = "Realisations"
    weight = 1
    identifier ="realisations"
    url = "realisations/"
[[menu.main]]
    name = "Lab"
    weight = 2
    url = "lab/"


[Languages]
[Languages.fr]
weight = 1
languageCode = "fr"
languageName = "French"
description = "Bastien Cornier, Creative & Front-end Developer Freelance based in France. Offers original and innovative experiences for web agencies, startups and companies."
[Languages.fr.params]
locale = "fr"
RSSLink = "/index.xml"
author = "Bastien Cornier" # add your company name
github = "https://github.com/Bastou/" # add your github profile name
twitter = "https://twitter.com/BastienCornier" # add your twitter profile
email = "bastien.cornier@gmail.com"


[Languages.en]
weight = 2
languageCode = "en"
languageName = "English"
description = "Bastien Cornier, Creative & Front-end Developer Freelance based in France. Offers original and innovative experiences for web agencies, startups and companies."
[Languages.en.params]
locale = "en"
languageName = "English"
author = "Bastien Cornier" # add your company name
github = "https://github.com/Bastou/" # add your github profile name
twitter = "https://twitter.com/BastienCornier" # add your twitter profile
email = "bastien.cornier@gmail.com"
link-realisation-title = "work"
link-lab-title = "lab"

[[Languages.en.menu.main]]
    name = "Work"
    weight = 1
    identifier ="realisations"
    url = "realisations/"
[[Languages.en.menu.main]]
    name = "Lab"
    weight = 2
    url = "lab/"